# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-12 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='user_review',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
