# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-15 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_user_details_user_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='user_detail',
        ),
    ]
