# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-30 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumers',
            name='user_semester',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
