# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-31 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_consumers_user_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumers',
            name='user_address',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
