# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-31 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_consumers_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumers',
            name='user_college',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumers',
            name='user_postalcode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
