# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-25 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_author', models.CharField(max_length=50)),
                ('book_printed_year', models.IntegerField()),
                ('book_name', models.CharField(max_length=100)),
                ('book_semester', models.IntegerField()),
                ('book_branch', models.CharField(max_length=100)),
                ('book_price', models.IntegerField()),
                ('book_condition', models.CharField(max_length=100)),
            ],
        ),
    ]
