# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-10 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_owner_username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
