# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-11 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170910_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_condition',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
