# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-14 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_book_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_condition',
            new_name='book_status',
        ),
    ]
